// src/routes/daf.tsx
import dafRenderer from 'daf-renderer';
import { createEffect, createSignal, Show } from 'solid-js';
import { createRouteData, useRouteData } from 'solid-start';
import Dropdown from '~/components/Dropdown';

type Daf = { main: string; rashi: string; tosafot: string };

// TODO: to make stuff selectable we need to parse the html better and split everything up into lines so that there is no blocky behaviour.
export function routeData() {
	return createRouteData(async () => {
		//how to use a local url
		const response = await fetch(
			'http://127.0.0.1:3000/api/getSample?masechta=brachot&daf=1'
		);
		return (await response.json()) as Daf;
	});
}
export default function Daf() {
	const data = useRouteData<typeof routeData>();
	const [loading, setLoading] = createSignal(true);
	const [masechta, setMasechta] = createSignal('brachot');

	createEffect(() => {
		const renderer = dafRenderer('#daf-container', {
			contentWidth: '600px',
			fontSize: {
				side: '10.5px',
			},
			padding: {
				vertical: '10px',
			},
			lineHeight: {
				main: '16px',
			},
			mainWidth: '42%',
			lineBreaks: 'br',
		});
		setTimeout(function () {
			renderer.render(data().main, data().rashi, data().tosafot, 'b');
		}, 100);
		setLoading(false);
	});

	const masechtot = [
		'brachot',
		'shabbat',
		'eruvin',
		'pesachim',
		'shekalim',
		'yoma',
		'sukkah',
		'beitzah',
		'rosh hashana',
		'taanit',
		'megillah',
		'moed katan',
		'chagigah',
		'yevamot',
		'ketubot',
		'nedarim',
		'nazir',
		'sotah',
		'gitin',
		'kidushin',
		'bava kamma',
		'bava metzia',
		'bava batra',
		'sanhedrin',
		'makkot',
		'shevuot',
		'avodah zarah',
		'horayot',
		'zevachim',
		'menachot',
		'chullin',
		'bechorot',
		'arachin',
		'temurah',
		'keritot',
		'meilah',
		'tamid',
		'middot',
		'kinot',
		'niddah',
	];

	return (
		<main class='mx-auto text-gray-700 p-4'>
			<h1>Daf</h1>
			<Dropdown
				options={masechtot}
				option={masechta}
				setOption={setMasechta}
			></Dropdown>
			<div class='hidden'>{JSON.stringify(data())}</div>
			<Show when={loading()}>
				<p>Loading...</p>
			</Show>
			<div class='pl-50 w-[660px]'>
				<div
					class='select-auto block'
					id='daf-container'
				></div>
			</div>
		</main>
	);
}

// src/routes/daf/+page.svelte
<!-- 
	
<main class='mx-auto text-gray-700 p-4'>
			<h1>Daf</h1>
			<form class='flex'>
				<Dropdown
					options={masechtot}
					option={masechta}
					setOption={setMasechta}
				></Dropdown>
				<button
					type='submit'
					on:click={() => {
						setSearchParams({ masechta: masechta() });
						newData(masechta());
					}}
				>
					Get Daf
				</button>
			</form>

			<div class='pl-50 w-[660px]'>
				<div
					class='select-auto block'
					id='daf-container'
				></div>
			</div>
		</main>

        import dafRenderer from 'daf-renderer';





<script>
const masechtot = [
    'Brachot',
    'Shabbat',
    'Eruvin',
    'Pesachim',
    'Shekalim',
    'Yoma',
    'Sukkah',
    'Beitzah',
    'RoshHashana',
    'Taanit',
    'megillah',
    'moed katan',
    'chagigah',
    'yevamot',
    'ketubot',
    'nedarim',
    'nazir',
    'sotah',
    'gitin',
    'kidushin',
    'bava kamma',
    'bava metzia',
    'bava batra',
    'sanhedrin',
    'makkot',
    'shevuot',
    'avodah zarah',
    'horayot',
    'zevachim',
    'menachot',
    'chullin',
    'bechorot',
    'arachin',
    'temurah',
    'keritot',
    'meilah',
    'tamid',
    'middot',
    'kinot',
    'niddah',
];

    const response = await fetch(
        `http://127.0.0.1:3000/api/getDaf?masechta=${masechta}&daf=1`
    );
    const newD = (await response.json()) as Daf;



      const options =   {contentWidth: '600px',
        fontSize: {
            side: '10.5px',
        },
        padding: {
            vertical: '10px',
        },
        lineHeight: {
            main: '16px',
        },
        mainWidth: '42%',
        lineBreaks: 'br',
    }
   
</script> -->
